export const dataContacts = [
  {
    _id: '1',
    name: 'Johana',
    phone: '1138321921',
    secundaryPhone: '1538321921',
    email: 'johanarezabala@gmail.com',
    businness: 'Ailalia',
    owner: 'Johana Rezabala',
    channel: 'whatsapp',
  },
  {
    _id: '2',
    name: 'Ezequiel Rivas',
    phone: '1138321921',
    secundaryPhone: '1538321921',
    email: 'ezequiel@gmail.com',
    businness: 'Elipse Chat',
    owner: 'Ezequiel Rivas',
    channel: 'whatsapp',
  },
  {
    _id: '3',
    name: 'Julian Avalos',
    phone: '11-78893530',
    secundaryPhone: '',
    email: 'julian@gmail.com',
    businness: 'Ailalia',
    owner: 'Julian Avalos',
    channel: 'whatsapp',
  },
  {
    _id: '4',
    name: 'Sergio',
    phone: '11-38321921',
    secundaryPhone: '',
    email: 'sergios@gmail.com',
    businness: 'Elipse Chat',
    owner: 'Sergio Ramos',
    channel: 'whatsapp',
  },
];
